package clientutils;

public enum Status
{
	
	INVALID_USERNAME_OR_PASSWORD,
	USER_LOGGED_IN,
	USERNAME_ACCEPTED,
	NOT_LOGGED_IN,
	BAD_COMMAND_SEQUENCE,
	SUCCESSFUL_FILE_OPERATION,
	ACTION_NOT_TAKEN,
	COMMAND_NOT_IMPLEMENTED,
	FILE_DOES_NOT_EXIST, QUITING_SERVICE, SYNTAX_ERROR_IN_REQUEST,
	COMMAND_NOT_RECOGNIZED, EXPECT_FILE

}
